Work around SwiftPM build regression affecting packages with C++ targets
apple/swift-testing pull request #188
Opened 2024-01-17 22:22 UTC by stmontgomery

This is a workaround to the SwiftPM issue being fixed here:

https://github.com/apple/swift-package-manager/pull/7267

2024-01-17 22:22 UTC, stmontgomery commented
@swift-ci please test

2024-01-18 00:50 UTC, briancroom approved these changes

2024-01-18 01:05 UTC, grynspan requested changes
Given that a fix PR is open on SwiftPM and presumably will be merged shortly, I don't think we need to apply a workaround here. We can wait a couple more days.

2024-01-23 17:45 UTC, stmontgomery commented
No longer relevant, the SwiftPM bug was fixed!

2024-01-23 17:45 UTC, closed without merging