Update swift-syntax links to swiftlang/swift-syntax
apple/swift-testing pull request #503
Opened 2024-06-25 14:19 UTC by ahoppen

2024-06-25 14:19 UTC, ahoppen commented
@swift-ci Please test

2024-06-25 14:22 UTC, dennisweissmann commented on Package@swift-6.0.swift
Did you accidentally bring that back?

2024-06-25 15:52 UTC, stmontgomery requested changes
Thanks for fixing these references!

As @dennisweissmann mentioned, could you either explain why the Package@swift-6.0 file is being restored, or else remove it if that was accidental?

2024-06-26 04:18 UTC, ahoppen commented on Package@swift-6.0.swift
Oh yes. It must have re-appeared during a rebase.

2024-06-26 04:19 UTC, ahoppen commented
@swift-ci Please test

2024-06-26 04:28 UTC, stmontgomery approved these changes

2024-06-26 04:29 UTC, dennisweissmann approved these changes

2024-06-26 04:57 UTC, merged