Support setting a debugger breakpoint to pause when a test fails
apple/swift-testing pull request #63
Opened 2023-10-14 03:35 UTC by stmontgomery

Add a function with a well-defined symbol that gets invoked whenever a failure occurs. This allows an attached debugger to place a breakpoint on that symbol and pause execution whenever a test failure is recorded.

### Motivation:

It's often helpful when investigating a test failure to attach using a debugger and place a breakpoint to step through the code. And sometimes, you want to pause exactly at the spot where a test failure occurs, instead of at the beginning of a particular test. This makes that workflow possible by establishing a function for which you can create a symbolic breakpoint, so that execution will pause whenever a test failure occurs.

### Modifications:

- Introduce a new function which is called whenever a test failure is recorded. Open to naming improvement suggestions!
- Allow configuring this "failure breakpoint" in `Configuration` to facilitate unit testing.
- Add new unit tests.

### Result:

It is possible to set a symbolic breakpoint on this new function and pause upon failure.

Resolves rdar://116948062

2023-10-14 03:35 UTC, stmontgomery commented
@swift-ci please test

2023-10-14 14:17 UTC, grynspan commented
Is the intent here just to provide a named function that can be used as a breakpoint target? If so, we can probably call it directly from post(). We will also want to annotate the C++ function with a few attributes to make sure clang doesn't optimize it away.

2023-10-16 02:54 UTC, stmontgomery commented
@swift-ci please test

2023-10-16 03:10 UTC, stmontgomery commented
> Is the intent here just to provide a named function that can be used as a breakpoint target? If so, we can probably call it directly from post().

I wanted to make it a `Configuration` property for a couple reasons:

- It facilitates unit testing, which the new tests in this PR demonstrate.
- When integrating with tools, this `Configuration` property provides the _option_ of calling a pre-existing function/symbol, which may be useful in case the tool already has some debugging support it wants to integrate with.

But customizing this new `Configuration` property is not _necessary_ to take advantage of this new feature. This PR intentionally defaults to a new, documented symbol which this library provides directly, and this makes the feature usable even when directly attached via a debugger, without other intermediary tools involved.

> We will also want to annotate the C++ function with a few attributes to make sure clang doesn't optimize it away.

Definitely! I [included](https://github.com/apple/swift-testing/pull/63/files#diff-e4c99e48fcfc7209c4f7c2d0b960874acb7e2cb318687994ff32d039da9c53a4R26) `__attribute__((noinline)) __attribute__((disable_tail_calls)) SWT_SENDABLE` — are there other/different attributes you think are needed?

2023-10-16 12:04 UTC, grynspan commented
> When integrating with tools, this Configuration property provides the option of calling a pre-existing function/symbol

Seems like this is more easily solved by having the tool, in its implemented event handler, call that function directly. I am not sure we actually need any code changes at all to support such a workflow.

2023-10-21 14:36 UTC, grynspan commented on Sources/Testing/Issues/Issue+Recording.swift
> +@_cdecl("SWTFailureBreakpoint")
Nitpick: the style we're using for C/C++ symbols is `swt_camelCase()`. We should either make this name match that style (`swt_failureBreakpoint()`) or change our style to be consistent.

2023-10-21 14:36 UTC, grynspan requested changes
C naming nitpick.

2023-10-23 20:01 UTC, stmontgomery commented
@swift-ci please test

2023-10-23 20:06 UTC, grynspan approved these changes

2023-10-23 20:06 UTC, grynspan commented
:shipit:

2023-10-29 01:43 UTC, stmontgomery commented
@swift-ci please test

2023-10-30 14:29 UTC, merged